config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about" ,as: "about"
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
   resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
 end
  resources :users, only: [:index,:show,:edit,:update] do
   resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  get 'search' => 'searchs#search', as: 'search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to:user
  belongs_to:book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 has_many :favorites, dependent: :destroy
 has_many :books, dependent: :destroy
 has_many :book_comments, dependent: :destroy

 # フォローをした、されたの関係
 has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
 has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

 # 一覧画面で使う
 has_many :followings, through: :relationships, source: :followed
 has_many :followers, through: :reverse_of_relationships, source: :follower
  has_one_attached :profile_image


  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true ,presence: true
  validates :introduction, length: { maximum: 50 }
  
   # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end



  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except:[:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def after_sign_in_path_for(resource)
    current_user
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book=Book.find(params[:book_id])
    # comment=current_user.book_comments.new(book_comment_params) ストロングぱらめーたの値を()に入れる
    comment=BookComment.new(book_comment_params)
    comment.user_id=current_user.id
    comment.book_id=book.id
    comment.save
    redirect_to book_path(book)
  end


  def destroy
    BookComment.find_by(params[:id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def show
    @book_new=Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment=BookComment.new
  end

  def index
    @books = Book.all
    @book = Book.new
    @user=current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice]="successfully"
      redirect_to book_path(@book)
    else
      @books=Book.all
      @user=current_user
      render 'index'
    end
  end

 def edit
     @book = Book.find(params[:id])
 end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book) , notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book=Book.find(params[:book_id])
    # favoritesテーブル.new(空のモデル)book_id(カラム名):book(book.findのbook)
    favorite=current_user.favorites.new(book_id:book.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    book=Book.find(params[:book_id])
    favorite=current_user.favorites.find_by(book_id:book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  # フォローするとき
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end
  # フォロー外すとき
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end
  # フォロー一覧
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end
  # フォロワー一覧
  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def search
    # viewのform_tagにて
    # 選択したmodelの値を@modelに代入。
    @model = params["model"]
    # 選択した検索方法の値を@methodに代入。
    @method = params["method"]
    # 検索ワードを@contentに代入。
    @content = params["content"]
    # @model, @content, @methodを代入した、
    # search_forを@recordsに代入。
    @records = search_for(@model, @content, @method)

  end

  private
  def search_for(model, content, method)
    # 選択したモデルがuserだったら
    if model == 'user'
      # 選択した検索方法がが完全一致だったら
      if method == 'perfect'
        User.where(name: content)
      # 選択した検索方法がが部分一致だったら
      elsif method == 'backward'
        User.where('name LIKE ?', '%'+content)
      elsif method == 'forward'
        User.where('name LIKE ?', content+'%')
      elsif method == 'partial'
        User.where('name LIKE ?', '%'+content+'%')
      end
    # 選択したモデルがbookだったら
    elsif model == 'book'
     if method == 'perfect'
        Book.where(title: content)
     elsif method == 'backward'
        Book.where('title LIKE ?', '%'+content)
     elsif method == 'forward'
        Book.where('title LIKE ?', content+'%')
     elsif method == 'partial'
        Book.where('title LIKE ?', '%'+content+'%')
     end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user=User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user=User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      @books=@user.books
      @book=Book.new
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_comment.html.erb
<table><% books.book_comments.each do |book_comment| %>

   <tr>
    <td>
    <%= attachment_image_tag book_comment.user, :profile_image, format: 'jpeg',size: "50x50",fallback: "no_image.jpg" %><br>
    <%=link_to user_path(books.user.id) do %><%= book_comment.user.name %><% end %></td>


    <td><%= book_comment.comment %></td>
  <!--<% if book_comment.user == current_user %>#コメント削除のところ。-->
    <td><%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete,remote: true,class:"btn btn-danger" %></td>

  <% end %>
  </tr>
  <% end %>

 </table>

 <div class="form-group">
  <label for="newcomment">Comment</label>

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <% if book.favorited_by?(current_user) %>
           <p>
           <td><%= link_to book_favorites_path(book), method: :delete do %>
              ❤️<%= book.favorites.count %> いいね
              <% end %></td>
           </p>
            <% else %>
           <p><td>
             <%= link_to book_favorites_path(book), method: :post do %>
              ♡<%= book.favorites.count %> いいね
              <% end %>
           </td></p>
          <% end %>
          <td><%= link_to "#{book.book_comments.count}コメント",book_path(book.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<%= form_for(@book) do |f| %>
<% if @book.errors.any? %>
	<h3><%= @book.errors.count %>error occurrence</h3>errors
	<ul>
		<% @book.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
<% end %>

<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book, class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<%= form_for(@book) do |f| %>
<% if @book.errors.any? %>
	<h3><%= @book.errors.count %>error occurrence</h3>errors
	<ul>
		<% @book.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
<% end %>

<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book_new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <% if @book.favorited_by?(current_user) %>
           <p>
          <td><%= link_to book_favorites_path(@book), method: :delete do %>
              ❤️<%= @book.favorites.count %> いいね
              <% end %></td>
           </p>
           <% else %>
           <p>
          <td><%= link_to book_favorites_path(@book), method: :post do %>
              ♡<%= @book.favorites.count %> いいね
              <% end %></td>
           </p>>
          <% end %>
          <td>コメント数<%= @book.book_comments.count %></td>

          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
            <% end %>
        </tr>
      </table>
     <div>
      <% @book.book_comments.each do |book_comment| %>
       <p><%= image_tag book_comment.user.get_profile_image %></p>
       <%= book_comment.user.name %>
       <%= book_comment.created_at.strftime('%Y/%m/%d') %><%= book_comment.comment %>
     </div>

     <div>
       <% if book_comment.user == current_user %>
       <%= link_to "Destroy" ,book_book_comment_path(book_comment.book,book_comment), method: :delete %>
       <% end %>
      <% end %>
    </div>

     <div>
       <%= form_with model: [@book,@book_comment] do |f| %>
        <%= f.text_area :comment, rows: '5',placeholder: "コメントをここに" %>
        <%= f.submit "送信する" %>
      <% end %>
     </div>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in',new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to 'Sign Up',new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/relationships/_follow_list.html.erb
<% if users.exists? %>
  <% users.each do |user| %>
    <table>
      <thead>
        <tr>
          <th>name</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= user.name %></td>
          <td>フォロー数: <%= user.followings.count %></td>
          <td>フォロワー数: <%= user.followers.count %></td>
        </tr>
      </tbody>
    </table>
  <% end %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followers.html.erb
   <div class='col-md-11 offset-md-1'>
    <table class='table table-hover table-inverse'>
      <h2>Follow User</h2>
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
      <% if @users.exists? %>
        <% @users.each do |user| %>
        <tr>
          <td><%= image_tag user.get_profile_image,size: '50x50' %></td>
          <td><%= user.name %></td>
          <td>フォロー数: <%= user.followings.count %></td>
          <td>フォロワー数: <%= user.followers.count %></td>
        </tr>
      </tbody>
    </table>
    </div>
  <% end %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followings.html.erb
    <table class='table table-hover table-inverse'>
      <h2>Follower User</h2>
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
      <% if @users.exists? %>
        <% @users.each do |user| %>
        <tr>
          <td><%= image_tag user.get_profile_image,size: '50x50' %></td>
          <td><%= user.name %></td>
          <td>フォロー数: <%= user.followings.count %></td>
          <td>フォロワー数: <%= user.followers.count %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/searchs/_form.html.erb
<% if user_signed_in? %>
    <%= form_tag(search_path, method: :get) do %>
      <%= text_field_tag 'content' %>
      <%= select_tag 'model', options_for_select({ "User" => "user", "Book" => "book" }) %>
      <%= select_tag 'method', options_for_select({"完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial"}) %>
      <%= submit_tag '検索' %>
    <% end %>
<% end %>

app/views/searchs/search.html.erb
<% if @model == 'user' %>
  <h3>検索ワード：<%= @content %></h3>
  <%= render 'users/index', users: @records %>
<% else @model == 'books' %>
  <h3>検索ワード：<%= @content %></h3>
    <%= render 'books/index', books: @records %>
<% end %>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数<%= user.followings.count %></td>
        <td>フォロワー数<%= user.followers.count %></td>
            <% unless user == current_user %>
            <% if current_user.following?(user) %>
        <td><%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %></td>
             <% else %>
        <td><%= link_to "フォローする", user_relationships_path(user.id), method: :post %></td>
             <% end %>
             <% end %>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>

  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>

  <tr>
    <!--~path(user)でuserという引数を持っていかなければならない-->
    <td><%= link_to "#{user.followings.count}フォロー数", user_followings_path(user) %></td>
    <td><%= link_to "#{user.followers.count}フォロワー数", user_followers_path(user) %></td>
  </tr>
</table>

<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/_users.html.erb
<% users.each do |user| %>
  <%= link_to user_path(user) do %>
    <%= user.name %><br>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
     <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
       <%= render 'info', user: current_user %>
     <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index',users: @users %>
      
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>